FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY service/package*.json ./service/

RUN npm ci

COPY service ./service

WORKDIR /app/service

RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && npm run go"]