export const DEFAULT_START_TIME = '09:00'
export const DEFAULT_END_TIME = '09:30'

export const OFFICE_START_HOUR = 9
export const OFFICE_END_HOUR = 19

export const MINUTES_IN_HOUR = 60
export const MINUTES_IN_DAY = 24 * MINUTES_IN_HOUR
export const SECONDS_IN_MINUTE = 60

export const SLOT_DURATION_MINUTES = 30

export const MAX_BOOKING_DURATION_MINUTES = 4 * MINUTES_IN_HOUR

export const TIME_INPUT_STEP_SECONDS = SLOT_DURATION_MINUTES * SECONDS_IN_MINUTE

export const OFFICE_START_MINUTES = OFFICE_START_HOUR * MINUTES_IN_HOUR

export const OFFICE_END_MINUTES = OFFICE_END_HOUR * MINUTES_IN_HOUR

export const MAX_TITLE_LENGTH = 100

export const MIN_RECURRENCE_COUNT = 2
export const MAX_RECURRENCE_COUNT = 52
export const DEFAULT_RECURRENCE_COUNT = 2
