services:
  roomly_service:
    build:
      context: .
      dockerfile: service/dockerfile
    volumes:
      - ./service:/app/service
      - /app/node_modules
      - /app/dist
    command: npm run dev # Use dev for hot-reloading during development
    env_file:
      - .env
      - .env.prod
    environment:
      FRONTEND_URL: http://localhost:3030
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    networks:
      - app-network
