services:
  roomly_service:
    build:
      context: .
      dockerfile: service/dockerfile
    depends_on:
      roomly_postgres:
        condition: service_healthy
    volumes:
      - ./service:/app/service
      - /app/node_modules
      - /app/dist
    command: sh -c "npx prisma migrate deploy && npm run dev" # Use dev for hot-reloading during development
    env_file:
      - .env
      - .env.prod
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    networks:
      - app-network
