services:
  roomly_postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env.prod
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: roomly_network
