services:
  roomly_postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env.prod
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: roomly_network
