services:
  roomly_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - '3030:3030'
    networks:
      - app-network
