FROM node:22-alpine AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci


FROM node:22-alpine AS development

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3030
ENV HOSTNAME=0.0.0.0

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

EXPOSE 3030

CMD ["npm", "run", "dev"]


FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN npm run build


FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3030
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3030

CMD ["node", "server.js"]